export const standardPlan = [
  "Up to a 20% FPS increase",
  "25 Tweaking tools",
  "100mb of tweaking scripts",
  "General Tweaks",
  "Performance Tweaks",
  "Network Tweaks",
  "Power Tweaks",
  "GPU Tweaks",
  "Registry Optimization",
  "Deep PC Debloating",
  "Fortnite Optimization"
];

export const goldPlan = [
  "Up to a 35% FPS increase",
  "450 Tweaking tools",
  "615mb of tweaking scripts",
  "1,746 files of scripts, tools, and others",
  "Modified",
  "Custom Windows modified according to the Specs of your device",
  "General Tweaks",
  "Performance Tweaks",
  "Advanced Tweaks",
  "Privacy Tweaks",
  "Network Tweaks",
  "Power Tweaks",
  "BIOS Optimisations",
  "GPU Tweaks",
  "USB Tweaks",
  "Mouse and Keyboard Tweaks",
  "Disable Windows Defender",
  "Uninstall Useless Preinstalled Apps",
  "Registry Optimization",
  "Deep PC Debloating",
  "Advanced Power Optimization",
  "NVIDIA, AMD, INTEL GPU Optimization",
  "Timer Resolution Guide",
  "Fix Corrupted Files",
  "Discord Optimization",
  "Fortnite Optimization"
];

export const ultimatePlan = [
  "Up to a 55% FPS increase",
  "450 Tweaking tools",
  "615mb of tweaking scripts",
  "1,746 files of scripts, tools, and others",
  "Modified",
  "Custom Windows modified according to the Specs of your device",
  "General Tweaks",
  "Performance Tweaks",
  "Advanced Tweaks",
  "Privacy Tweaks",
  "Network Tweaks",
  "Power Tweaks",
  "BIOS Optimisations",
  "GPU Tweaks",
  "USB Tweaks",
  "Mouse and Keyboard Tweaks",
  "Uninstall Useless Preinstalled Apps",
  "Registry Optimization",
  "Deep PC Debloating",
  "Advanced Power Optimization",
  "NVIDIA, AMD, INTEL GPU Optimization",
  "Timer Resolution Guide",
  "Fix Corrupted Files",
  "Discord Optimization",
  "Fortnite Optimization",
  "More than 25 Paid Tweaking Tools",
  "More than 15 Paid Custom Windows",
  "Ultimate Windows Debloating",
  "Lowest CPU Processes",
  "Disable Power Saving Features",
  "Performance Turbo Optimizer",
  "RAM Turbo Optimizer",
  "Disable Windows Defender",
  "Enable Turbo Boot",
  "50+ More Features"
];
